//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: media.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `MediaProto_imageClient`, then call methods of this protocol to make API calls.
internal protocol MediaProto_imageClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: MediaProto_imageClientInterceptorFactoryProtocol? { get }

  func imageUpload(
    _ request: MediaProto_ImageUploadRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<MediaProto_ImageUploadRequest, MediaProto_ImageUploadResponse>
}

extension MediaProto_imageClientProtocol {
  internal var serviceName: String {
    return "mediaProto.image"
  }

  /// Unary call to ImageUpload
  ///
  /// - Parameters:
  ///   - request: Request to send to ImageUpload.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func imageUpload(
    _ request: MediaProto_ImageUploadRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<MediaProto_ImageUploadRequest, MediaProto_ImageUploadResponse> {
    return self.makeUnaryCall(
      path: "/mediaProto.image/ImageUpload",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeImageUploadInterceptors() ?? []
    )
  }
}

internal protocol MediaProto_imageClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'imageUpload'.
  func makeImageUploadInterceptors() -> [ClientInterceptor<MediaProto_ImageUploadRequest, MediaProto_ImageUploadResponse>]
}

internal final class MediaProto_imageClient: MediaProto_imageClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: MediaProto_imageClientInterceptorFactoryProtocol?

  /// Creates a client for the mediaProto.image service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: MediaProto_imageClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

